### ISSUE TITLE
add Chainguard secdb to docker scout advisory feed

### ISSUE THREAD

**Issue by amdawson** [docker/scout-cli#10]
### Description

scout already supports the open source Wolfi security feed. But Chainguard also has a second feed for commercial packages. Please consider adding this feed to the scout advisory feed

https://packages.cgr.dev/chainguard/security.json

**Comment by thaJeztah** [comment]
Thanks! Moved the ticket 👍

**Comment by amdawson** [comment]
> > That's great, thank you. Maybe update docs to reflect? I didn't see issues, just saw the docs
> 
> That's a good point re docs. Thanks.
> 
> Just out of curiosity, do you happen to have access/can share a test image with some known CVEs in it we could use to test our support against?

Well, we try to keep them at 0, but sometimes some sneak in. try cgr.dev/chainguard/vault or cgr.dev/chainguard/maven

**Comment by cdupuis** [comment]
@ChrisChinchilla could add the Chainguard feed to the docs, please?

**Comment by ChrisChinchilla** [comment]
@cdupuis https://github.com/docker/docs/pull/17617

**Comment by cdupuis** [comment]
Thanks. Closing this here.

**Comment by MordodeMaru** [comment]
We are publishing both feeds in OSV format, if that helps, @cdupuis
