### ISSUE TITLE
Wrong package version detection for Oracle Linux

### ISSUE THREAD

**Issue by visortelle** [docker/scout-cli#110]
I believe `1:3.0.7-25.0.1.el9_3` and `2:3.0.7-25.0.1.ksplice1.el9_3` are the same version.

<img width="626" alt="Screenshot 2024-03-23 at 1 04 30 PM" src="https://github.com/docker/scout-cli/assets/9302460/42d8ff27-655d-4cb8-86c2-75e8214ee497">

Same for `2.34-83.0.2.el9_3.12 > 2:2.34-60.0.3.ksplice1.el9_2.7`.

<img width="684" alt="Screenshot 2024-03-23 at 1 06 54 PM" src="https://github.com/docker/scout-cli/assets/9302460/3ec1415d-7e06-4681-bfa8-2ab541e10fe6">

There are a few more packages affected by the same issue.

https://hub.docker.com/layers/library/oraclelinux/9-slim/images/sha256-f1bdd3635b56b12302434d86021141aceb1ca51d79457959cc8193922ee206eb?context=repo&tab=vulnerabilities
<img width="654" alt="Screenshot 2024-03-23 at 1 03 54 PM" src="https://github.com/docker/scout-cli/assets/9302460/a412b25a-0347-4964-be31-a025331dcdd3">

**Comment by cdupuis** [comment]
@visortelle thanks for raising this. It does look like something is not working as desired for oracle rpm packages. We’ll look into it and will report back.

**Comment by neilprosser** [comment]
@visortelle - we've made some amendments to the way we're checking the vulnerable ranges and the image is showing as free of vulnerabilities now.

Thanks again for reporting.

**Comment by visortelle** [comment]
@neilprosser - thank you for the fix.
