### ISSUE TITLE
/tmp is filling up

### ISSUE THREAD

**Issue by teodorescuserban** [docker/scout-cli#146]
Running scout 1.13.0 to scan a long list of images. My `/tmp` is using a 2GB of tmpfs. I do have a 100GB disk and would really want to use that.

I am using `DOCKER_SCOUT_CACHE_DIR=/srv/cache`  and I can see that this directory is indeed being used:

```
docker scout cache df
   ...
      Docker Scout temporary directory to generate SBOMs is located at:
   /srv/cache/docker-scout
  as defined in  DOCKER_SCOUT_CACHE_DIR  environment variable


                               Image Digest                               │  Size
──────────────────────────────────────────────────────────────────────────┼─────────
  sha256:0b009214526b443211cff5a3701cd6e0f998e1397d79908036b9616ade882591 │ 0 B
  sha256:16812f49a29229859fbeeb0e470d325bd0aff4e2667f28ee7c8f2d7fc07f192a │ 0 B
  sha256:2c6ab22ffba8ae1dff9dd26e2025e12736361e83f5cf57811395afd7e90c25cb │ 0 B
```

However, during every image pull, my `/tmp` is filling up with folders like `/tmp/stereoscope-2638175145`.  If the whole unpacked image is less than 2GB, docker scout will go ahead and index, cache, etc in the proper location.
Is there a way to make docker scout (or docker) use `/srv/tmp` instead for those directories when pulling?

Thank you!

**Comment by cdupuis** [comment]
Thanks for raising this @teodorescuserban. This is currently a known limitation of one of the OSS libraries the Scout CLI is using. Until this is fixed you should be able to set your `TMPDIR` env variable depending on your OS to `/srv` so that the `/tmp` directory is not going to be used for those cache folders.

**Comment by teodorescuserban** [comment]
> `TMPDIR` env variable

Oh if it's honouring this env var then I am fine with it. I guess I was not expecting to come to this. 😄

**Comment by teodorescuserban** [comment]
Just tested this. Works like a charm. Thank you, @cdupuis !

Closing as resolved. No need for yet another option when the basic stuff works properly 😄
