### ISSUE TITLE
Container platform is not included in CVES output

### ISSUE THREAD

**Issue by NeilJed** [docker/scout-cli#157]
I'm building multi-architecture images (amd64/arm64) and need to do separate Scout scans for each platform.

While the CLI default "packages" output includes the platform choses, the markdown summary output does not and makes it hard to tell which is which. This is very apparent when using the Docker Scout Action in a Github workflow as the PR notes/annotation doesn't indicate platform architecture the report is for.

<img width="826" alt="Screenshot 2024-08-27 at 16 25 17" src="https://github.com/user-attachments/assets/b9322a7b-2c1a-49a7-8912-9552953bc330">

versus:

<img width="640" alt="Screenshot 2024-08-27 at 16 26 02" src="https://github.com/user-attachments/assets/e9f7876f-bb09-4224-b727-fc9b6e9a40af">

Can we get the architecture being scanned included in the Markdown output?

**Comment by cdupuis** [comment]
This is definitely a bug that we will address. Thanks for reporting.

**Comment by cdupuis** [comment]
Pushed a fix which will be included in the next release.
