### ISSUE TITLE
CycloneDx File is invalid, because the License-Id does not match the official scheme of cyclonedx.org

### ISSUE THREAD

**Issue by NicolaSeitz** [docker/scout-cli#160]
Hi guys,

Using the newly added file-format cylonedx i'm able to create a cyclonedx-sbom from my docker image. 
When i do a validation of this file, i got a lot of errors because the License-Id does not match with the valid License-Id's given in http://cyclonedx.org/schema/spdx.schema.json.

An Example: The generated cyclonedx-file contains a dependency with a license "GPL-3+" which should be a  "GPL-3.0+" and so on. 

If you have any questions, I'm happy to help.

**Comment by cdupuis** [comment]
Thanks for raising this @NicolaSeitz. 

We implemented a fix which will go out with the next release of the CLI.

**Comment by NicolaSeitz** [comment]
Many thanks for the quick action :)
Do you know when the next release will be approximately?

**Comment by cdupuis** [comment]
> Do you know when the next release will be approximately?

We are trying to cut another release early next week. Hopefully that is soon enough.
