### ISSUE TITLE
Unicode characters \u003e & \u003c in sarif output instead of great-than and less-than symbols

### ISSUE THREAD

**Issue by zkarpinski** [docker/scout-cli#45]
When results are exported to sarif format, greater-than and less-than symbols are in unicode.

Steps to reproduce:

1. Using the latest v0.24.1 version of docker-scout
2. Run `docker-scout cves webgoat/webgoat:latest --format sarif --output test.sarif`
3. Open test.sarif with a plaintext editor like notepad or VS Code.
4. Observe **\u003e** & **\u003c** in place of > & < symbols.
5. 
![image](https://github.com/docker/scout-cli/assets/1206496/fd338b23-b33a-433c-ae9d-f91b08bb1445)

**Comment by eunomie** [comment]
Thanks for the report.
A fix is on its way, it will be part of the next release.
