### ISSUE TITLE
All my pipelines fail

### ISSUE THREAD

**Issue by K2ouMais** [docker/scout-cli#51]
Hello everyone,

I have pipelines, that put the build images into a *.tar archive, and these archive will be scanned on another step.

Seems that the ```--type archive``` is gone and all my pipelines fail with an error.

![Anmerkung 2023-09-25 075537](https://github.com/docker/scout-cli/assets/52510455/0ea1b627-0b9d-463d-97ea-5696d87ff2dc)

Ist this a wanted behaviour?

This has been running for weeks and failed today the first time.

**Comment by dvdksn** [comment]
👋🏻 hi @K2ouMais. We recently added support for specifying the artifact type via protocol prefixes for the image name. Could you try to update the command to the following format and see if it works?

```
cves archive:///tmp/${TAR_FILE} --only-severity critical,high
```

(note that the `--type` flag is removed and replaced by `archive://` prefix.)

**Comment by cdupuis** [comment]
@K2ouMais sorry for the breaking change and inconvenience this causing you. As Docker Scout matures from Early Access to GA, we had to make this change now rather than later.

As @dvdksn mentioned, please switch to using the `archive` prefix.

**Comment by K2ouMais** [comment]
That isnt mentioned in the documentation:
https://docs.docker.com/engine/reference/commandline/scout_cves/

The weird thing ist that the following commands dont work:
```
docker run -t -v $(pwd)/images:/tmp -e DOCKER_SCOUT_HUB_USER=${DOCKERHUB_USER} -e DOCKER_SCOUT_HUB_PASSWORD=${DOCKERHUB_PASSWORD} docker/scout-cli cves --type archive /tmp/${TAR_FILE} --only-severity critical,high`
```
```
docker run -t -v $(pwd)/images:/tmp -e DOCKER_SCOUT_HUB_USER=${DOCKERHUB_USER} -e DOCKER_SCOUT_HUB_PASSWORD=${DOCKERHUB_PASSWORD} docker/scout-cli:latest cves --type archive /tmp/${TAR_FILE} --only-severity critical,high`
```

But this one seems to work without a problem:
```
docker run -t -v $(pwd)/images:/tmp -e DOCKER_SCOUT_HUB_USER=${DOCKERHUB_USER} -e DOCKER_SCOUT_HUB_PASSWORD=${DOCKERHUB_PASSWORD} docker/scout-cli:0.24,1 cves --type archive /tmp/${TAR_FILE} --only-severity critical,high`
```

With other words, seems that the "0.24.1" isnt the latest after all.

**Comment by cdupuis** [comment]
It looks like the `docker/scout-cli:latest` was released a bit early. But you are effectively catching us between two releases (docs not updated etc). The `latest` version is now `1.0.1`. 

> Now I only have to fix all my pipeline :o(

I'm really sorry for this. Trust me, now that we are going 1.0.0, we'll follow SemVer.

**Comment by K2ouMais** [comment]
I think this thread can be closed, as there is a solution.

Thank you
