### ISSUE TITLE
Confusing results from docker scout cves on the fixed version vs the version exists

### ISSUE THREAD

**Issue by asankaf** [docker/scout-cli#62]
We tried executing `docker scout cves` on one of our docker images and got some confusing findings on the package shown in the screenshot here. We are using the latest non-vulnerable version of the package as you can see from the version numbers (They are exactly the same), but `docker scout cves` still tells us that the vulnerability still exists. 

![image](https://github.com/docker/scout-cli/assets/1999525/37b55bc6-65d0-4a7e-bf03-cf9f39b83406)

Any idea as to why is it behaving like that? Is it because of the existence of the revision number in the package version (v2.88.6.0 vs v2.88.6)?

/Asanka

**Comment by cdupuis** [comment]
Thanks @asankaf for this report. I have an idea where this is coming. Let us dig in. I’ll report back once we have a fix in place.

**Comment by asankaf** [comment]
Hi @whostolebenfrog, I can confirm that the issue is fixed now.
