### ISSUE TITLE
Seeing "panic: runtime error" when attempting to get policy results with the "wrong" org set

### ISSUE THREAD

**Issue by jonnyrobots** [docker/scout-cli#63]
<img width="1116" alt="image" src="https://github.com/docker/scout-cli/assets/13132227/82e247e2-bad3-470a-b914-39c485fca9df">

Repro

`docker scout config organization [orgA]`
`docker scout policy [image] --platform linux/amd64` (where image is in orgB)

Ok scenario

`docker scout config organization [orgB]`
`docker scout policy [image] --platform linux/amd64` (where image is in orgB)

**Comment by pnorton5432** [comment]
Thanks. We should fail in this case, but gracefully would be better!

Worth noting however, that you can evaluate a local image against arbitrary organization's policy sets. It just won't work to fetch existing results from registry.

I've fixed this upstream and it should be in the next release.
