### ISSUE TITLE
ERROR   Status: could not get repositories for org <org_name>: could not list skills: failed to list integration configurations: 403 403 Forbidden, CodEe: 1

### ISSUE THREAD

**Issue by JatinLodhi** [docker/scout-cli#83]
ERROR   Status: could not get repositories for org <org_name>: could not list skills: failed to list integration configurations: 403 403 Forbidden, CodEe: 1

**Comment by fdiogo** [comment]
Hello @JatinLodhi, thank you for raising this issue first of all.

Could I ask you to run `docker scout enroll <org_name>` and then try again?

**Comment by dloperab** [comment]
It worked for me..thanks @fdiogo!

**Comment by mblakew** [comment]
I recently ran into this issue as well while following the linked docker scout quickstart guide here: https://docs.docker.com/scout/quickstart/. Not sure who contributes to that page, but might be worth adding the `docker scout enroll <org_name>` step!

**Comment by cdupuis** [comment]
cc @dvdksn

**Comment by cdupuis** [comment]
Docs have been updated.
