### ISSUE TITLE
Finding vulnerabilities in python pip packages

### ISSUE THREAD

**Issue by gergelyfabian** [docker/scout-cli#85]
It seems `docker scout sbom` finds pip packages (type `pypi`).
However security vulnerabilities are not reported for them (for `docker scout cves`). Is this intentional?

**Comment by cdupuis** [comment]
@gergelyfabian, thanks for raising this. No, this isn't intentional. Do you have an example for us to investigate?

**Comment by gergelyfabian** [comment]
I have debugged this further. One reason was that I was only looking at critical cves. These are for other levels.
Then, I believe I could not see them because those are transitive CVEs.

E.g. oci==2.68.0 has cryptography as its dependency, and that package has a CVE (that is properly detected by docker scout).

**Comment by cdupuis** [comment]
Please re-open if you are still seeing issues with CVE reports on pip packages.
