### ISSUE TITLE
Compare/analyze SBOMs

### ISSUE THREAD

**Issue by MPV** [docker/scout-cli#97]
I've run into Docker Scout having issues trying to compare large images in CI:
- https://github.com/docker/scout-action/issues/21

...so I'd like Docker Scout to be able to compare SBOMs instead of passing entire/large images around. 

What's your thoughts on this?

**Comment by cdupuis** [comment]
@MPV, yes. We have an internal ticket to allow SBOMs to be used as input for the various commands. We’ll likely start with SPDX. Sound good?

**Comment by MPV** [comment]
Great to hear, music to my ears. 🎶🎷

**Comment by cdupuis** [comment]
@MPV, this should be possible now with `syft -o spdx-json alpine | docker scout cves sbom://`.
